#pragma once

/*** Process ***/
NTSTATUS XXIONTOpenProcess(PIONTOPENPROCESS_ARGS args);
NTSTATUS XXIONTSuspendProcess(PIONTSUSPENDPROCESS_ARGS args);
NTSTATUS XXIONTResumeProcess(PIONTRESUMEPROCESS_ARGS args);
NTSTATUS XXIONTQuerySystemInformationEx(PIONTQUERYSYSTEMINFORMATIONEX_ARGS args);
NTSTATUS XXIONTQueryInformationProcess(PIONTQUERYINFORMATIONPROCESS_ARGS args);
NTSTATUS XXIONTSetInformationProcess(PIONTSETINFORMATIONPROCESS_ARGS args);
NTSTATUS XXIONTFlushInstructionCache(PIONTFLUSHINSTRUCTIONCACHE_ARGS args);

/*** Memory ***/
NTSTATUS XXIONTAllocateVirtualMemory(PIONTALLOCATEVIRTUALMEMORY_ARGS args);
NTSTATUS XXIONTFlushVirtualMemory(PIONTFLUSHVIRTUALMEMORY_ARGS args);
NTSTATUS XXIONTFreeVirtualMemory(PIONTFREEVIRTUALMEMORY_ARGS args);
NTSTATUS XXIONTLockVirtualMemory(PIONTLOCKVIRTUALMEMORY_ARGS args);
NTSTATUS XXIONTUnlockVirtualMemory(PIONTUNLOCKVIRTUALMEMORY_ARGS args);
NTSTATUS XXIONTProtectVirtualMemory(PIONTPROTECTVIRTUALMEMORY_ARGS args);
NTSTATUS XXIONTReadVirtualMemory(PIONTREADVIRTUALMEMORY_ARGS args);
NTSTATUS XXIONTWriteVirtualMemory(PIONTWRITEVIRTUALMEMORY_ARGS args);
NTSTATUS XXIONTQueryVirtualMemory(PIONTQUERYVIRTUALMEMORY_ARGS args);

/*** Thread ***/
NTSTATUS XXIONTOpenThread(PIONTOPENTHREAD_ARGS args);
NTSTATUS XXIONTCreateThreadEx(PIONTCREATETHREADEX_ARGS args);
NTSTATUS XXIONTQueryInformationThread(PIONTQUERYINFORMATIONTHREAD_ARGS args);
NTSTATUS XXIONTSetInformationThread(PIONTSETINFORMATIONTHREAD_ARGS args);
NTSTATUS XXIONTGetContextThread(PIONTGETCONTEXTTHREAD_ARGS args);
NTSTATUS XXIONTSetContextThread(PIONTSETCONTEXTTHREAD_ARGS args);
NTSTATUS XXIONTResumeThread(PIONTRESUMETHREAD_ARGS args);
NTSTATUS XXIONTSuspendThread(PIONTSUSPENDTHREAD_ARGS args);

/*** Sync ***/
NTSTATUS XXIONTWaitForSingleObject(PIONTWAITFORSINGLEOBJECT_ARGS args);

/*** Handle ***/
NTSTATUS XXIONTDuplicateObject(PIONTDUPLICATEOBJECT_ARGS args);
NTSTATUS XXIOIsWow64Process(PIOISWOW64PROCESS_ARGS args);